Instruction to add ROOT_URL
My first deployment failed because of:
Error: Must pass options.rootUrl or set ROOT_URL in the server environment

I googled this error message and found this article http://architects.dzone.com/articles/meteor-nodejs-app-heroku-5 (sorry it's your competitor ;)) so I simply added this variable in my app's environment and the 2nd deployment was successful !

HTH